export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SELECT_ITEM = 'SELECT_ITEM';
export const MAKE_ITEM_ACTIVE = 'MAKE_ITEM_ACTIVE';
export const REMOVE_CURRENT_ITEM = 'REMOVE_CURRENT_ITEM';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_ALL_COMMENTS = 'REMOVE_ALL_COMMENTS';
